name: Tests

on: push

jobs:
  tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            platform: linux-gcc CXX=g++-12
          - os: ubuntu-26.04
            platform: linux-gcc CXX=g++-13
          - os: ubuntu-26.04
            platform: linux-gcc CXX=g++-14
          - os: ubuntu-26.04
            platform: linux-gcc CXX=g++-15
          - os: ubuntu-24.04
            platform: linux-clang CXX=clang++-16
          - os: ubuntu-24.04
            platform: linux-clang CXX=clang++-17
          - os: ubuntu-24.04
            platform: linux-clang CXX=clang++-18
          - os: ubuntu-26.04
            platform: linux-clang CXX=clang++-20
          - os: ubuntu-26.04
            platform: linux-clang CXX=clang++-21
          - os: ubuntu-26.04
            platform: linux-clang CXX=clang++-22
          - os: ubuntu-26.04
            platform: linux-gcc
            container: quay.io/pypa/manylinux_2_28_x86_64

          - os: ubuntu-24.04-arm
            platform: linux-gcc
          - os: ubuntu-24.04-arm
            platform: linux-clang
          - os: ubuntu-26.04-arm
            platform: linux-gcc
          - os: ubuntu-26.04-arm
            platform: linux-clang
          - os: ubuntu-26.04-arm
            platform: linux-gcc
            container: quay.io/pypa/manylinux_2_28_aarch64

          - os: windows-2022
            platform: win-vs-32
          - os: windows-2022
            platform: win-vs-64
          - os: windows-2025
            platform: win-vs-32
          - os: windows-2025
            platform: win-vs-64
          - os: windows-11-arm
            platform: win-vs-arm64

          - os: macos-15
            platform: macos-clang-arm64
          - os: macos-15-intel
            platform: macos-clang-64
          - os: macos-26
            platform: macos-clang-arm64
          - os: macos-26-intel
            platform: macos-clang-64

    steps:
      - uses: actions/checkout@v6

      - if: startsWith(matrix.os, 'windows')
        name: Windows - Set up MSVC
        uses: TheMrMilchmann/setup-msvc-dev@v4
        with:
          arch: ${{ endswith(matrix.platform, '-64') && 'x64' || endswith(matrix.platform, '-arm64') && 'arm64' || 'x86' }}

      - if: startsWith(matrix.os, 'windows')
        name: Windows - Install make
        run: choco install --no-progress -y make

      - name: Compile tests
        run: make PLATFORM=${{ matrix.platform }} -k -C tests compile
        env:
          C_FLAGS: $(treat_warnings_as_errors)

      - name: Run tests
        run: make PLATFORM=${{ matrix.platform }} -k -C tests test
